### ISSUE TITLE
Manual helm v2 install without Tiller on EKS - unknown field "affinity"

### ISSUE THREAD

**Issue by bliu-rei** [lucidworks/fusion-cloud-native#17]
Following your instructions under **Use Helm to Install Fusion**, subsection **Don't want to use Tiller? (Helm v2)**, on to AWS EKS cluster:

- For LoadBalancer service type, [service annotation is required for EKS](https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html)
  - `service.beta.kubernetes.io/aws-load-balancer-type: nlb` for public facing
  - `service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0` for private facing
  so we must use customization values.yaml. In our case, EKS is private only, so the customized values.yaml content is as follows:

```
sql-service:
  service:
    thrift:
      type: "ClusterIP"
api-gateway:
  service:
    annotations: { service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0 }
```

With the above, and with RELEASE and NAMESPACE both set to 'f5', run `kubectl apply -f "${RELEASE}_${NAMESPACE}_fusion_install.yaml" --namespace "${NAMESPACE}"`, got validation error:
```
error: error validating "f5_f5_fusion_install.yaml": error validating data: ValidationError(Deployment.spec): unknown field "affinity" in io.k8s.api.apps.v1.DeploymentSpec; if you choose to ignore these errors, turn validation off with --validate=false
```

Rerun kubectl with `--validate=false`, deployment succeeds, and http://<internal-load-balancer-of-api-gateway-service>:6764 from Chrome brings up a log in page!
