### ISSUE TITLE
Helm Fails To install Fusion Platform On Minikube

### ISSUE THREAD

**Issue by razilevin** [lucidworks/fusion-cloud-native#196]
Failed to install the fusion platform on **minikube**

fusion-platform: 5.4.0
minikube: v1.23.0
k8s: 1.22.1

Command used to install fusion platform
`./minikube_fusion-platform_fusion_upgrade_fusion.sh`

Error
`Error: failed to install CRD crds/seldon-core-operator-crd.yaml: unable to recognize "": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1`

Please note that in the version of k8s that minikube uses by default does not support this API version
`customresourcedefinitions         crd,crds     apiextensions.k8s.io/v1                false        CustomResourceDefinition`

Thank You

**Comment by razilevin** [comment]
After further tweaks,

Many of these fixes might be just because I am not familiar with the chart or a different  version of  kubernetes  as the default for minikube is 1.22.x does not work.

Maybe this helps someone...

This will bring up kubernetes with a version that allows the installation to complete.
`minikube start -p fusion-platform --cpus=4 --memory=16g --nodes=1 --kubernetes=1.20.0`

Add the following to your values.xml
`securityContext:
  fsGroup: 1337
  runAsUser: 1337`
  
since the default 8993 does not work.
  
Run your generated script
  
After 15 minutes or so....

You will need to fix the role binding to include a new API Group for these rules. The rule is named 
`fusion-ambassador` namespace `the namespace you installed your chart`

```
 - verbs:
      - get
      - list
      - watch
    apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
  - verbs:
      - update
    apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses/status`
```

Delete the ambassador pod so it gets recreated with the new role binding

Run `minikube -p fusion-platform service list` to get the ip/port of proxy
